version: "3.8"
services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MISTRAL_API_KEY=Qm4kD3Ge9phVSsTjxu069woCSyVAV0Pf
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
